// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctzjsvnjixdkayzjzjmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0empzdm5qaXhka2F5emp6am1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NjkzMDgsImV4cCI6MjA2ODM0NTMwOH0.ugRX3HmL1rX1SDdgAS-SMsgyMqwrrAkcSc5CM5qUwlQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});